---
stages:
  - build
  - test
  - review
  - staging
  - production

before_script:
  - export TAG=${CI_COMMIT_SHA}
  - export BRANCH=${CI_COMMIT_REF_NAME}
  - export REGISTRY_HOST=${CI_REGISTRY}
  - export REGISTRY_URI="/${CI_PROJECT_PATH}"

build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --target hyrax-engine-dev --tag $CI_REGISTRY_IMAGE:$TAG .
    - docker push $CI_REGISTRY_IMAGE:$TAG
  tags:
    - local

lint:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  script:
    - bundle check || bundle
    - bundle exec rubocop
  tags:
    - docker

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  services:
    - name: selenium/standalone-chrome:3.141
      alias: chrome
    - name: bitnami/postgresql:12.6.0
      alias: db
    - name: samvera/fcrepo4:4.7.5
      alias: fcrepo
    - name: redis:5-alpine
      alias: redis
    - name: solr:8.7
      alias: solr
      command: [ "sh", "-c", "precreate-core", "hyrax_test", "/opt/solr/server/configsets/hyraxconf" ]
  variables:
    DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
    DATABASE_URL: "postgres://postgres:postgres@db/hyku"
    FCREPO_HOST: "fcrepo"
    FCREPO_PORT: 8080
    FCREPO_REST_PATH: "rest"
    POSTGRES_DB: "hyku"
    POSTGRES_HOST: "db"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_USER: "postgres"
    REDIS_HOST: "redis"
    REDIS_PORT: 6379
    GIT_STRATEGY: none
    SOLR_HOST: solr
    SOLR_PORT: 8983
    SOLR_TEST_CORE: hyrax_test
    SOLR_TEST_URL: http://solr:8983/solr/hyrax_test
    SOLR_CORE_NAME: "hyrax_test"
    SOLR_CONFIG_DIR: "solr/config"
    SOLR_CONFIGSET: blacklight-core
    SOLR_CONFIGSET_SOURCE_PATH: solr/config
  script:
    - cd /app/samvera/hyrax-engine && bundle exec rspec
  tags:
    - docker

review:
  stage: review
  type: deploy
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: http://web.$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.staging.$SITE_URI_BASE
    on_stop: stop_review
  only:
    - branches
  except:
    - master
  script:
    - echo "deploying"
    - sleep 10
    - echo "totally fake deploy"
  tags:
    - local

stop_review:
  stage: review
  script:
    - echo "STOP"
  when: manual
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop

staging:
  stage: staging
  type: deploy
  script:
    - echo "stage!"
  only:
    - master
  tags:
    - local

production:
  stage: production
  type: deploy
  script:
    - echo "prod!"
  when: manual
  only:
    - master
  tags:
    - local
