analytics:
  google:
    app_name: notch8-qa
    app_version: 0.0.1
    privkey_path: /notch8-qa-057daeb77b4d.p12
    privkey_secret: notasecret
    client_email: server-account@notch8-qa.iam.gserviceaccount.com
